### ISSUE TITLE
ReferenceError: ethers is not defined

### ISSUE THREAD

**Issue by JulianWe** [JulianWe/price-bot#12]
```sh
/usr/src/app/index.js:34
const uniswapV2 = new ethers.Contract(
                  ^

ReferenceError: ethers is not defined
    at Object.<anonymous> (/usr/src/app/index.js:34:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

**Comment by JulianWe** [comment]
adding  `ehters` and `money-legos` should resolv the issue

```sh
    "@studydefi/money-legos": "^2.4.1",
    "ethers": "^5.0.26"
```

```sh
{
  "name": "price-bot",
  "version": "0.3.0",
  "description": "Uniswap & Kyberswap Price Monitor",
  "engines": {
    "node": "10"
  },
  "main": "index.js",
  "scripts": {
    "start": "node index.js",
    "test": "node test.js"
  },
  "dependencies": {
    "axios": "^0.19.2",
    "console.table": "^0.10.0",
    "dotenv": "^8.2.0",
    "ejs": "^2.5.6",
    "express": "^4.15.2",
    "infura-web3-provider": "0.0.3",
    "lodash": "^4.17.15",
    "moment": "^2.25.3",
    "moment-timezone": "^0.5.28",
    "numeral": "^2.0.6",
    "web3": "1.2.9",
    "@studydefi/money-legos": "^2.4.1",
    "ethers": "^5.0.26"
  },
  "devDependencies": {
    "request": "^2.81.0"
  },
  "license": "MIT"
}
```
