### ISSUE TITLE
SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by JulianWe** [JulianWe/price-bot#13]
```sh
/usr/src/app/node_modules/ethers/lib.commonjs/abi/abi-coder.js:113
    #getCoder(param) {
    ^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/src/app/node_modules/ethers/lib.commonjs/abi/index.js:15:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/src/app/node_modules/ethers/lib.commonjs/ethers.js:11:18)
```

**Comment by JulianWe** [comment]
```sh
"ethers": "^5.0.26",
"@studydefi/money-legos": "2.4.2"
```
