### ISSUE TITLE
ReferenceError: provider is not defined

### ISSUE THREAD

**Issue by JulianWe** [JulianWe/price-bot#14]
```sh
/usr/src/app/index.js:46
  provider
  ^

ReferenceError: provider is not defined
    at Object.<anonymous> (/usr/src/app/index.js:46:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

**Comment by JulianWe** [comment]
// ETHERS CONFIG
const provider = new ethers.providers.JsonRpcProvider(process.env.RPC_URL);
