### ISSUE TITLE
Error: invalid contract address or ENS name (argument="addressOrName", value=undefined, code=INVALID_ARGUMENT, version=contracts/5.7.0)

### ISSUE THREAD

**Issue by JulianWe** [JulianWe/price-bot#15]
```sh
/usr/src/app/node_modules/@ethersproject/logger/lib/index.js:247
        throw this.makeError(message, code, params);
        ^

Error: invalid contract address or ENS name (argument="addressOrName", value=undefined, code=INVALID_ARGUMENT, version=contracts/5.7.0)
    at Logger.makeError (/usr/src/app/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/usr/src/app/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at Logger.throwArgumentError (/usr/src/app/node_modules/@ethersproject/logger/lib/index.js:250:21)
    at Contract.BaseContract (/usr/src/app/node_modules/@ethersproject/contracts/lib/index.js:669:20)
    at new Contract (/usr/src/app/node_modules/@ethersproject/contracts/lib/index.js:1053:42)
    at Object.<anonymous> (/usr/src/app/index.js:44:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

**Comment by JulianWe** [comment]
Using the right Contract `UniswapV2Router02` should resolv the issue
```sh
// Contract UniswapV2Router02 https://etherscan.io/address/0x7a250d5630b4cf539739df2c5dacb4c659f2488d#code
const uniswapV2 = new ethers.Contract(
  '0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D',
  [
    'function getAmountsOut(uint256 amountIn, address[] calldata path) external view returns (uint256[] memory amounts)',
    'function WETH() external pure returns (address)'
  ],
  provider
);
```
