### ISSUE TITLE
Error: missing revert data in call exception; Transaction reverted without a reason string 

### ISSUE THREAD

**Issue by JulianWe** [JulianWe/price-bot#17]
```sh
{ Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"to":"0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D","data":"0xd06ca61f0000000000000000000000000000000000000000000000000de0b6b3a764000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000002000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e5831","accessList":null}, error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":62,\"error\":{\"code\":-32000,\"message\":\"execution reverted\"}}","error":{"code":-32000},"requestBody":"{\"method\":\"eth_call\",\"params\":[{\"to\":\"0x7a250d5630b4cf539739df2c5dacb4c659f2488d\",\"data\":\"0xd06ca61f0000000000000000000000000000000000000000000000000de0b6b3a764000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000002000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e5831\"},\"latest\"],\"id\":62,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://mainnet.infura.io/v3/5309f62fbf1f41eb97e16033efed3ca4"}, code=CALL_EXCEPTION, version=providers/5.7.2)
    at Logger.makeError (/usr/src/app/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/usr/src/app/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at checkError (/usr/src/app/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:108:16)
    at JsonRpcProvider.<anonymous> (/usr/src/app/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:751:47)
    at step (/usr/src/app/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/usr/src/app/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/usr/src/app/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  reason:
   'missing revert data in call exception; Transaction reverted without a reason string',
  code: 'CALL_EXCEPTION',
  data: '0x',
  transaction:
   { to: '0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D',
     data:
      '0xd06ca61f0000000000000000000000000000000000000000000000000de0b6b3a764000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000002000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e5831',
     accessList: null },
  error:
   { Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":62,\"error\":{\"code\":-32000,\"message\":\"execution reverted\"}}", error={"code":-32000}, requestBody="{\"method\":\"eth_call\",\"params\":[{\"to\":\"0x7a250d5630b4cf539739df2c5dacb4c659f2488d\",\"data\":\"0xd06ca61f0000000000000000000000000000000000000000000000000de0b6b3a764000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000002000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e5831\"},\"latest\"],\"id\":62,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://mainnet.infura.io/v3/5309f62fbf1f41eb97e16033efed3ca4", code=SERVER_ERROR, version=web/5.7.1)
       at Logger.makeError (/usr/src/app/node_modules/@ethersproject/logger/lib/index.js:238:21)
       at Logger.throwError (/usr/src/app/node_modules/@ethersproject/logger/lib/index.js:247:20)
       at /usr/src/app/node_modules/@ethersproject/web/lib/index.js:313:32
       at step (/usr/src/app/node_modules/@ethersproject/web/lib/index.js:33:23)
       at Object.next (/usr/src/app/node_modules/@ethersproject/web/lib/index.js:14:53)
       at fulfilled (/usr/src/app/node_modules/@ethersproject/web/lib/index.js:5:58)
       at process._tickCallback (internal/process/next_tick.js:68:7)
     reason: 'processing response error',
     code: 'SERVER_ERROR',
     body:
      '{"jsonrpc":"2.0","id":62,"error":{"code":-32000,"message":"execution reverted"}}',
     error:
      { Error: execution reverted
          at getResult (/usr/src/app/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:191:21)
          at processJsonFunc (/usr/src/app/node_modules/@ethersproject/web/lib/index.js:356:22)
          at /usr/src/app/node_modules/@ethersproject/web/lib/index.js:288:46
          at step (/usr/src/app/node_modules/@ethersproject/web/lib/index.js:33:23)
          at Object.next (/usr/src/app/node_modules/@ethersproject/web/lib/index.js:14:53)
          at fulfilled (/usr/src/app/node_modules/@ethersproject/web/lib/index.js:5:58)
          at process._tickCallback (internal/process/next_tick.js:68:7) code: -32000, data: undefined },
     requestBody:
      '{"method":"eth_call","params":[{"to":"0x7a250d5630b4cf539739df2c5dacb4c659f2488d","data":"0xd06ca61f0000000000000000000000000000000000000000000000000de0b6b3a764000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000002000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e5831"},"latest"],"id":62,"jsonrpc":"2.0"}',
     requestMethod: 'POST',
     url:
      'https://mainnet.infura.io/v3/5309f62fbf1f41eb97e16033efed3ca4' } }
```

**Comment by JulianWe** [comment]
Maybe: The result of calling a function that existed in the ABI I was using, but not in the actual contract deployed on the Blockchain. In other words, I supplied the wrong contract address when I created the contract using new ethers.Contract(address, ABI, signer)

**Comment by JulianWe** [comment]
Wrong Token Contract for USDC in this case Token Contract for Layer 2 '0xaf88d065e77c8cC2239327C5EDb3A432268e5831' https://arbiscan.io/address/0xaf88d065e77c8cC2239327C5EDb3A432268e5831

```sh
    await checkPair({
      inputTokenSymbol: 'WETH',
      inputTokenAddress: WETH_ADDRESS,
      outputTokenSymbol: 'USDC',
      outputTokenAddress: '0xaf88d065e77c8cC2239327C5EDb3A432268e5831',
      inputAmount: parseUnits('1', 18)
    })
```

**Comment by JulianWe** [comment]
or setting correct `RPC_URL` should resolv the issue
```sh
RPC_URL_TESTNET="https://goerli.infura.io/v3/<API_KEY>"
RPC_URL="https://mainnet.infura.io/v3/<API_KEY>"
PRIVATE_KEY=""
ACCOUNT=""
```
