### ISSUE TITLE
ReferenceError: web3 is not defined

### ISSUE THREAD

**Issue by JulianWe** [JulianWe/price-bot#18]
```sh
ReferenceError: web3 is not defined
    at monitorPrice (/usr/src/app/index.js:166:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by JulianWe** [comment]
replace  `inputAmount: web3.utils.toWei('1', 'ETHER')` with `inputAmount: parseUnits('1', 18)`
```sh  
   await checkPair({
      inputTokenSymbol: 'WETH',
      inputTokenAddress: WETH_ADDRESS,
      outputTokenSymbol: 'UBT',
      outputTokenAddress: '0x8400D94A5cb0fa0D041a3788e395285d61c9ee5e',
      inputAmount: parseUnits('1', 18)
    })

    await checkPair({
      inputTokenSymbol: 'WETH',
      inputTokenAddress: WETH_ADDRESS,
      outputTokenSymbol: 'GETH',
      outputTokenAddress: '0xdD69DB25F6D620A7baD3023c5d32761D353D3De9',
      inputAmount: web3.utils.toWei('1', 'ETHER')
    })

```
