### ISSUE TITLE
Error: Provider not set or invalid

### ISSUE THREAD

**Issue by JulianWe** [JulianWe/price-bot#2]
```sh
Checking prices...
Error: Provider not set or invalid
    at Object.InvalidProvider (/usr/src/app/node_modules/web3-core-helpers/src/errors.js:38:16)
    at RequestManager.send (/usr/src/app/node_modules/web3-core-requestmanager/src/index.js:128:32)
    at sendRequest (/usr/src/app/node_modules/web3-core-method/src/index.js:560:42)
    at send (/usr/src/app/node_modules/web3-core-method/src/index.js:581:13)
    at Object._executeMethod (/usr/src/app/node_modules/web3-eth-contract/src/index.js:826:24)
    at checkPair (/usr/src/app/index.js:45:96)
    at monitorPrice (/usr/src/app/index.js:79:11)
    at Timeout.setInterval [as _onTimeout] (/usr/src/app/index.js:123:48)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

**Comment by JulianWe** [comment]
set RPC_URL provider in .env file
