### ISSUE TITLE
TypeError: web3.eth.Contract is not a constructor

### ISSUE THREAD

**Issue by JulianWe** [JulianWe/price-bot#4]
```sh
/usr/src/app/index.js:23
const uniswapFactoryContract = new web3.eth.Contract(UNISWAP_FACTORY_ABI, UNISWAP_FACTORY_ADDRESS)

TypeError: web3.eth.Contract is not a constructor
    at Object.<anonymous> (/usr/src/app/index.js:23:32)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

**Comment by JulianWe** [comment]
setting web3 package version: "web3": "1.2.9" https://web3js.readthedocs.io/en/v1.2.0/web3-eth-contract.html#id28
