### ISSUE TITLE
Error: Invalid number of parameters for "getExpectedRate". Got 4 expected 3!

### ISSUE THREAD

**Issue by JulianWe** [JulianWe/price-bot#8]
```sh
Error: Invalid number of parameters for "getExpectedRate". Got 4 expected 3!
    at Object.InvalidNumberOfParams (/usr/src/app/node_modules/web3-core-helpers/src/errors.js:32:16)
    at Object._createTxObject (/usr/src/app/node_modules/web3-eth-contract/src/index.js:813:22)
    at checkPair (/usr/src/app/index.js:46:53)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by JulianWe** [comment]
let kyberResult = await kyberRateContract.methods.getExpectedRate(inputTokenAddress, outputTokenAddress, inputAmount, true).call()  remove 'true' from old contract function getExpectedRate - usePermissionless (bool) resolved the issue
